version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - C:\Users\alexe\source\repos\WebDocker\app:/var/lib/mysql
    restart: always
     
  app:
    depends_on:
      - db
    image: webdocker
    build:
      context: .
      dockerfile: ./WebDocker/Dockerfile
    restart: always
    ports: 
      - 80:80

volumes:
    dbdata: